version: "3.9"  # optional since v1.27.0
services:
  web_api:
    build: . # build the Docker image 
    image: bsaproductcrudapi
    container_name: web_api_application6
    ports:
      - "5000:80"
  sql:
    image: "mcr.microsoft.com/mssql/server:latest"
    container_name: my_sql_server2
    ports: # not actually needed, because the two services are on the same network
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=A!VeryComplex123Password
